# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift-Protobuf' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift-Protobuf
  pod 'SwiftProtobuf', git: 'https://github.com/apple/swift-protobuf.git', :tag => '0.9.902'
  pod 'Alamofire', '~> 4.4'
 
  target 'Swift-ProtobufTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Swift-ProtobufUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
