// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class RKUser;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - RKUserRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface RKUserRoot : GPBRootObject
@end

#pragma mark - RKUser

typedef GPB_ENUM(RKUser_FieldNumber) {
  RKUser_FieldNumber_Id_p = 1,
  RKUser_FieldNumber_Name = 2,
  RKUser_FieldNumber_Mobile = 4,
};

@interface RKUser : GPBMessage

@property(nonatomic, readwrite) int32_t id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mobile;

@end

#pragma mark - RKUserList

typedef GPB_ENUM(RKUserList_FieldNumber) {
  RKUserList_FieldNumber_UsersArray = 1,
  RKUserList_FieldNumber_HasMore = 2,
  RKUserList_FieldNumber_Info = 3,
};

@interface RKUserList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RKUser*> *usersArray;
/** The number of items in @c usersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger usersArray_Count;

@property(nonatomic, readwrite) BOOL hasMore;

@property(nonatomic, readwrite, copy, null_resettable) NSString *info;

@end

#pragma mark - RKUserRequest

typedef GPB_ENUM(RKUserRequest_FieldNumber) {
  RKUserRequest_FieldNumber_Id_p = 1,
  RKUserRequest_FieldNumber_Type = 2,
};

@interface RKUserRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** basic, whole */
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@end

#pragma mark - RKUserListRequest

typedef GPB_ENUM(RKUserListRequest_FieldNumber) {
  RKUserListRequest_FieldNumber_Type = 1,
  RKUserListRequest_FieldNumber_PageNumber = 2,
  RKUserListRequest_FieldNumber_PageCount = 3,
};

@interface RKUserListRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite) int32_t pageNumber;

@property(nonatomic, readwrite) int32_t pageCount;

@end

#pragma mark - RKErrorResponse

typedef GPB_ENUM(RKErrorResponse_FieldNumber) {
  RKErrorResponse_FieldNumber_Code = 1,
  RKErrorResponse_FieldNumber_Message = 2,
};

@interface RKErrorResponse : GPBMessage

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

#pragma mark - RKSimpleInfo

typedef GPB_ENUM(RKSimpleInfo_FieldNumber) {
  RKSimpleInfo_FieldNumber_Title = 1,
  RKSimpleInfo_FieldNumber_Info = 2,
};

@interface RKSimpleInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *info;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
