// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	User
	UserList
	UserRequest
	UserListRequest
	ErrorResponse
	SimpleInfo
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id     int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Mobile string `protobuf:"bytes,4,opt,name=mobile" json:"mobile,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type UserList struct {
	Users   []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
	HasMore bool    `protobuf:"varint,2,opt,name=has_more,json=hasMore" json:"has_more,omitempty"`
	Info    string  `protobuf:"bytes,3,opt,name=info" json:"info,omitempty"`
}

func (m *UserList) Reset()                    { *m = UserList{} }
func (m *UserList) String() string            { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()               {}
func (*UserList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserList) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *UserList) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

func (m *UserList) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type UserRequest struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
}

func (m *UserRequest) Reset()                    { *m = UserRequest{} }
func (m *UserRequest) String() string            { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()               {}
func (*UserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type UserListRequest struct {
	Type       string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	PageNumber int32  `protobuf:"varint,2,opt,name=page_number,json=pageNumber" json:"page_number,omitempty"`
	PageCount  int32  `protobuf:"varint,3,opt,name=page_count,json=pageCount" json:"page_count,omitempty"`
}

func (m *UserListRequest) Reset()                    { *m = UserListRequest{} }
func (m *UserListRequest) String() string            { return proto.CompactTextString(m) }
func (*UserListRequest) ProtoMessage()               {}
func (*UserListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserListRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UserListRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *UserListRequest) GetPageCount() int32 {
	if m != nil {
		return m.PageCount
	}
	return 0
}

type ErrorResponse struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *ErrorResponse) Reset()                    { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()               {}
func (*ErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ErrorResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ErrorResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SimpleInfo struct {
	Title string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Info  string `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *SimpleInfo) Reset()                    { *m = SimpleInfo{} }
func (m *SimpleInfo) String() string            { return proto.CompactTextString(m) }
func (*SimpleInfo) ProtoMessage()               {}
func (*SimpleInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SimpleInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SimpleInfo) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*UserList)(nil), "UserList")
	proto.RegisterType((*UserRequest)(nil), "UserRequest")
	proto.RegisterType((*UserListRequest)(nil), "UserListRequest")
	proto.RegisterType((*ErrorResponse)(nil), "ErrorResponse")
	proto.RegisterType((*SimpleInfo)(nil), "SimpleInfo")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xd9, 0x6d, 0xd3, 0x3f, 0x53, 0x54, 0x08, 0x22, 0x11, 0x11, 0x4b, 0x4e, 0x7b, 0x2a,
	0xa8, 0xe0, 0xcd, 0x8b, 0xe2, 0x41, 0x50, 0x0f, 0x11, 0xbd, 0x2e, 0xbb, 0xdd, 0x69, 0x1b, 0xd8,
	0x24, 0x6b, 0x92, 0x3d, 0xf8, 0xed, 0x25, 0xd9, 0xa6, 0xf5, 0xf6, 0xde, 0xdb, 0xcc, 0x9b, 0x1f,
	0xb3, 0x00, 0xbd, 0x43, 0xbb, 0xea, 0xac, 0xf1, 0x86, 0x3f, 0xc1, 0xf8, 0xcb, 0xa1, 0xa5, 0xa7,
	0x90, 0xcb, 0x86, 0x65, 0xcb, 0xac, 0x20, 0x22, 0x97, 0x0d, 0xa5, 0x30, 0xd6, 0x95, 0x42, 0x96,
	0x2f, 0xb3, 0x62, 0x2e, 0xa2, 0xa6, 0x17, 0x30, 0x51, 0xa6, 0x96, 0x2d, 0xb2, 0x71, 0x4c, 0xf7,
	0x8e, 0x7f, 0xc3, 0x2c, 0x74, 0xbc, 0x49, 0xe7, 0xe9, 0x15, 0x90, 0xd0, 0xee, 0x58, 0xb6, 0x1c,
	0x15, 0x8b, 0x3b, 0xb2, 0x0a, 0x5f, 0xc4, 0x90, 0xd1, 0x4b, 0x98, 0xed, 0x2a, 0x57, 0x2a, 0x63,
	0x87, 0xe2, 0x99, 0x98, 0xee, 0x2a, 0xf7, 0x6e, 0x2c, 0x86, 0x7d, 0x52, 0x6f, 0x0c, 0x1b, 0x0d,
	0xfb, 0x82, 0xe6, 0xb7, 0xb0, 0x88, 0xd3, 0xf8, 0xd3, 0xa3, 0xf3, 0xff, 0x10, 0xe7, 0x09, 0xd1,
	0xff, 0x76, 0x07, 0xc4, 0xa0, 0x39, 0xc2, 0x59, 0x42, 0x49, 0x63, 0xe9, 0x59, 0x76, 0x7c, 0x46,
	0x6f, 0x60, 0xd1, 0x55, 0x5b, 0x2c, 0x75, 0xaf, 0x6a, 0xb4, 0xb1, 0x81, 0x08, 0x08, 0xd1, 0x47,
	0x4c, 0xe8, 0x35, 0x44, 0x57, 0xae, 0x4d, 0xaf, 0x7d, 0x84, 0x22, 0x62, 0x1e, 0x92, 0xe7, 0x10,
	0xf0, 0x47, 0x38, 0x79, 0xb1, 0xd6, 0x58, 0x81, 0xae, 0x33, 0xda, 0x45, 0xfc, 0xb5, 0x69, 0x70,
	0x7f, 0xc0, 0xa8, 0x29, 0x83, 0xa9, 0x42, 0xe7, 0xaa, 0x6d, 0x42, 0x4c, 0x96, 0x3f, 0x00, 0x7c,
	0x4a, 0xd5, 0xb5, 0xf8, 0xaa, 0x37, 0x86, 0x9e, 0x03, 0xf1, 0xd2, 0xb7, 0x89, 0x70, 0x30, 0x87,
	0x83, 0xe4, 0xc7, 0x83, 0xd4, 0x93, 0xf8, 0xcf, 0xee, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0b,
	0x4f, 0xd8, 0x1e, 0xc1, 0x01, 0x00, 0x00,
}
